### ISSUE TITLE
Improve information about example usage with ansi-terminal

### ISSUE THREAD

**Issue by h7x4** [muesli4/table-layout#55]
Hello! This is just a question.

I'm having some problems trying to use this package with `ansi-terminal`. In the README at [Improving Readability of Grids](https://github.com/muesli4/table-layout#improving-readability-of-grids), it says the following:

> Big grids are usually not that readable. To improve their readability, two functions are provided:
> 
> - `altLines` will apply the given function in an alternating pattern. E.g., color every second row grey.
> - `checkeredCells` will checker cells with 2 different functions.
> A good way to use this would be the [ansi-terminal package](http://hackage.haskell.org/package/ansi-terminal), provided you are using a terminal to output your text.

However, `ansi-terminal` uses `IO` actions as their means to change color:

```haskell
main :: IO ()
main = do
  setSGR [ SetColor Foreground Vivid Red
         , SetColor Background Vivid Blue ]
  putStrLn "Red-On-Blue"
  setSGR [Reset]  -- Reset to default colour scheme
  putStrLn "Default colors."
```

Which in turn causes the type of any colored text to be `IO ()`. Unless there is some kind of table printer where I can provide a function `String -> IO ()` per cell during printing the table (which rules out `gridString` and `gridLines`), I'm not able to figure out any other way for these to cooporate.

Am I missing something, or is this just fundamentally impossible? If it does somehow work, I would really like an example in the README.

**Comment by muesli4** [comment]
Hello @h7x4,

you can use the following to get character sequences that cause the expected behavior:
```
> setSGRCode [SetColor Foreground Dull Red]
"\ESC[31m"
> setSGRCode [Reset]
"\ESC[0m"
```
This should be used in combination with `Text.Layout.Cell.Formatted`.  For an example see [my comment here](https://github.com/muesli4/table-layout/issues/4#issuecomment-569075594).  With the version on GitHub more complex nested formatting is possible.  The release is still pending but may be ready soon.

If you don't mind, I will keep this issue open as a reminder to improve the `README.md`.
